// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_9d2411bd3bdef3e9, []int{0}
}
func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (dst *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(dst, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protomsgs.MessageData")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_9d2411bd3bdef3e9) }

var fileDescriptor_common_9d2411bd3bdef3e9 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x91, 0xed, 0xba, 0xf5, 0xd5, 0xed, 0x70, 0x43, 0xd1, 0x50, 0x8a, 0x28, 0x1d, 0x34,
	0x75, 0xe9, 0x2b, 0x74, 0x09, 0x21, 0x10, 0x34, 0x64, 0x97, 0x2d, 0x21, 0x04, 0x91, 0x64, 0x7c,
	0xca, 0x90, 0x07, 0xcc, 0x7b, 0x05, 0x0b, 0x43, 0x92, 0xe9, 0xfe, 0xef, 0xbb, 0xbb, 0xe1, 0x87,
	0x7e, 0x4c, 0x21, 0xa4, 0xf8, 0x3b, 0xcd, 0x29, 0x27, 0xec, 0xca, 0x08, 0xe4, 0xe8, 0xfb, 0xc2,
	0xe0, 0x75, 0x67, 0x89, 0xb4, 0xb3, 0xff, 0x3a, 0x6b, 0xfc, 0x81, 0xb7, 0xf1, 0xe8, 0x6d, 0xcc,
	0x07, 0x3b, 0x93, 0x4f, 0x91, 0x33, 0xc1, 0x64, 0xa7, 0x1e, 0x25, 0x7e, 0x42, 0x97, 0x7d, 0xb0,
	0x94, 0x75, 0x98, 0x78, 0x25, 0x98, 0xac, 0xd5, 0x4d, 0xe0, 0x3b, 0x54, 0xde, 0xf0, 0xba, 0x3c,
	0x56, 0xde, 0xe0, 0x07, 0xb4, 0x2e, 0x11, 0xf9, 0x89, 0x37, 0x82, 0xc9, 0x17, 0xb5, 0xd2, 0xe2,
	0x63, 0x32, 0x76, 0x63, 0xf8, 0x53, 0xb9, 0x5d, 0x09, 0xbf, 0x00, 0x96, 0xb4, 0x3f, 0x0d, 0x5b,
	0x7b, 0xe6, 0xad, 0x60, 0xb2, 0x57, 0x77, 0x06, 0x11, 0x1a, 0xf2, 0x2e, 0xf2, 0xe7, 0xb2, 0x29,
	0x79, 0x68, 0x4b, 0xa5, 0xbf, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x19, 0x17, 0xb3, 0xe9,
	0x00, 0x00, 0x00,
}
