// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node/protocols/protomsgs/discovery.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoveryMessage int32

const (
	DiscoveryMessage_DiscoveryReq DiscoveryMessage = 0
	DiscoveryMessage_DiscoveryRes DiscoveryMessage = 1
)

var DiscoveryMessage_name = map[int32]string{
	0: "DiscoveryReq",
	1: "DiscoveryRes",
}
var DiscoveryMessage_value = map[string]int32{
	"DiscoveryReq": 0,
	"DiscoveryRes": 1,
}

func (x DiscoveryMessage) String() string {
	return proto.EnumName(DiscoveryMessage_name, int32(x))
}
func (DiscoveryMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_discovery_0556aee6809c4bd7, []int{0}
}

type DiscoveryMsgData struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	InitNodeID           string       `protobuf:"bytes,2,opt,name=initNodeID" json:"initNodeID,omitempty"`
	Expiry               uint32       `protobuf:"varint,3,opt,name=Expiry" json:"Expiry,omitempty"`
	TTL                  uint32       `protobuf:"varint,4,opt,name=TTL" json:"TTL,omitempty"`
	InitHash             string       `protobuf:"bytes,5,opt,name=InitHash" json:"InitHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DiscoveryMsgData) Reset()         { *m = DiscoveryMsgData{} }
func (m *DiscoveryMsgData) String() string { return proto.CompactTextString(m) }
func (*DiscoveryMsgData) ProtoMessage()    {}
func (*DiscoveryMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_0556aee6809c4bd7, []int{0}
}
func (m *DiscoveryMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryMsgData.Unmarshal(m, b)
}
func (m *DiscoveryMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryMsgData.Marshal(b, m, deterministic)
}
func (dst *DiscoveryMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryMsgData.Merge(dst, src)
}
func (m *DiscoveryMsgData) XXX_Size() int {
	return xxx_messageInfo_DiscoveryMsgData.Size(m)
}
func (m *DiscoveryMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryMsgData proto.InternalMessageInfo

func (m *DiscoveryMsgData) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *DiscoveryMsgData) GetInitNodeID() string {
	if m != nil {
		return m.InitNodeID
	}
	return ""
}

func (m *DiscoveryMsgData) GetExpiry() uint32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *DiscoveryMsgData) GetTTL() uint32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *DiscoveryMsgData) GetInitHash() string {
	if m != nil {
		return m.InitHash
	}
	return ""
}

// a protocol define a set of reuqest and responses
type DiscoveryRequest struct {
	DiscoveryMsgData *DiscoveryMsgData `protobuf:"bytes,1,opt,name=discoveryMsgData" json:"discoveryMsgData,omitempty"`
	// method specific data
	Message              DiscoveryMessage `protobuf:"varint,2,opt,name=message,enum=protomsgs.DiscoveryMessage" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_0556aee6809c4bd7, []int{1}
}
func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (dst *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(dst, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetDiscoveryMsgData() *DiscoveryMsgData {
	if m != nil {
		return m.DiscoveryMsgData
	}
	return nil
}

func (m *DiscoveryRequest) GetMessage() DiscoveryMessage {
	if m != nil {
		return m.Message
	}
	return DiscoveryMessage_DiscoveryReq
}

type DiscoveryResponse struct {
	DiscoveryMsgData *DiscoveryMsgData `protobuf:"bytes,1,opt,name=discoveryMsgData" json:"discoveryMsgData,omitempty"`
	// response specific data
	Message              DiscoveryMessage `protobuf:"varint,2,opt,name=message,enum=protomsgs.DiscoveryMessage" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_0556aee6809c4bd7, []int{2}
}
func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (dst *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(dst, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetDiscoveryMsgData() *DiscoveryMsgData {
	if m != nil {
		return m.DiscoveryMsgData
	}
	return nil
}

func (m *DiscoveryResponse) GetMessage() DiscoveryMessage {
	if m != nil {
		return m.Message
	}
	return DiscoveryMessage_DiscoveryReq
}

func init() {
	proto.RegisterType((*DiscoveryMsgData)(nil), "protomsgs.DiscoveryMsgData")
	proto.RegisterType((*DiscoveryRequest)(nil), "protomsgs.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "protomsgs.DiscoveryResponse")
	proto.RegisterEnum("protomsgs.DiscoveryMessage", DiscoveryMessage_name, DiscoveryMessage_value)
}

func init() {
	proto.RegisterFile("node/protocols/protomsgs/discovery.proto", fileDescriptor_discovery_0556aee6809c4bd7)
}

var fileDescriptor_discovery_0556aee6809c4bd7 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x51, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x35, 0x4e, 0xa7, 0xbb, 0x53, 0x89, 0x79, 0x18, 0x61, 0x82, 0x8c, 0x82, 0x50, 0x7c, 0xe8,
	0x40, 0x51, 0xfc, 0x80, 0x8a, 0x0e, 0x9c, 0x0f, 0x61, 0x3f, 0x50, 0xdb, 0x50, 0x03, 0x36, 0xa9,
	0xbd, 0x51, 0xdc, 0x6f, 0xe8, 0x9f, 0xf8, 0x85, 0xb2, 0xb4, 0xab, 0xa1, 0xb2, 0x67, 0xdf, 0xee,
	0x3d, 0xf7, 0x9c, 0xc3, 0x39, 0x09, 0x84, 0xda, 0x64, 0x72, 0x5a, 0x56, 0xc6, 0x9a, 0xd4, 0xbc,
	0x60, 0x3d, 0x15, 0x98, 0xe3, 0x34, 0x53, 0x98, 0x9a, 0x77, 0x59, 0x2d, 0x23, 0x87, 0xb1, 0x41,
	0x7b, 0x1a, 0x9f, 0x6d, 0x14, 0xa5, 0xa6, 0x28, 0x8c, 0xae, 0x15, 0xc1, 0x37, 0x01, 0x1a, 0xaf,
	0x5d, 0xe6, 0x98, 0xc7, 0x89, 0x4d, 0xd8, 0x0d, 0x0c, 0x0b, 0x89, 0x98, 0xe4, 0x72, 0xb5, 0x72,
	0x32, 0x21, 0xe1, 0xf0, 0x62, 0x14, 0xb5, 0x16, 0xd1, 0xfc, 0xf7, 0x2a, 0x7c, 0x2a, 0x3b, 0x05,
	0x50, 0x5a, 0xd9, 0x47, 0x93, 0xc9, 0x59, 0xcc, 0xb7, 0x27, 0x24, 0x1c, 0x08, 0x0f, 0x61, 0x23,
	0xe8, 0xdf, 0x7e, 0x94, 0xaa, 0x5a, 0xf2, 0xde, 0x84, 0x84, 0x87, 0xa2, 0xd9, 0x18, 0x85, 0xde,
	0x62, 0xf1, 0xc0, 0x77, 0x1c, 0xb8, 0x1a, 0xd9, 0x18, 0xf6, 0x67, 0x5a, 0xd9, 0xfb, 0x04, 0x9f,
	0xf9, 0xae, 0xf3, 0x69, 0xf7, 0xe0, 0xd3, 0x0f, 0x2d, 0xe4, 0xeb, 0x9b, 0x44, 0xcb, 0xee, 0x80,
	0x66, 0x9d, 0x22, 0x4d, 0xf2, 0x13, 0x2f, 0x79, 0xb7, 0xab, 0xf8, 0x23, 0x62, 0x57, 0xb0, 0xd7,
	0x54, 0x72, 0x05, 0x8e, 0x36, 0xe8, 0x6b, 0x8a, 0x58, 0x73, 0x83, 0x2f, 0x02, 0xc7, 0x5e, 0x28,
	0x2c, 0x8d, 0x46, 0xf9, 0xdf, 0xa9, 0xce, 0xaf, 0xfd, 0xef, 0xad, 0x31, 0x46, 0xe1, 0xc0, 0x7f,
	0x3d, 0xba, 0xd5, 0x41, 0x90, 0x92, 0xa7, 0xbe, 0x33, 0xbf, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xab, 0x07, 0xc6, 0xb3, 0x7c, 0x02, 0x00, 0x00,
}
