// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node/protocols/protomsgs/inspectCont.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InspectContMsgData struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InspectContMsgData) Reset()         { *m = InspectContMsgData{} }
func (m *InspectContMsgData) String() string { return proto.CompactTextString(m) }
func (*InspectContMsgData) ProtoMessage()    {}
func (*InspectContMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_inspectCont_f57071f177f36f30, []int{0}
}
func (m *InspectContMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectContMsgData.Unmarshal(m, b)
}
func (m *InspectContMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectContMsgData.Marshal(b, m, deterministic)
}
func (dst *InspectContMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectContMsgData.Merge(dst, src)
}
func (m *InspectContMsgData) XXX_Size() int {
	return xxx_messageInfo_InspectContMsgData.Size(m)
}
func (m *InspectContMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectContMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_InspectContMsgData proto.InternalMessageInfo

func (m *InspectContMsgData) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

// a protocol define a set of reuqest and responses
type InspectContRequest struct {
	InspectContMsgData   *InspectContMsgData `protobuf:"bytes,1,opt,name=InspectContMsgData" json:"InspectContMsgData,omitempty"`
	ContainerID          string              `protobuf:"bytes,2,opt,name=containerID" json:"containerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InspectContRequest) Reset()         { *m = InspectContRequest{} }
func (m *InspectContRequest) String() string { return proto.CompactTextString(m) }
func (*InspectContRequest) ProtoMessage()    {}
func (*InspectContRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_inspectCont_f57071f177f36f30, []int{1}
}
func (m *InspectContRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectContRequest.Unmarshal(m, b)
}
func (m *InspectContRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectContRequest.Marshal(b, m, deterministic)
}
func (dst *InspectContRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectContRequest.Merge(dst, src)
}
func (m *InspectContRequest) XXX_Size() int {
	return xxx_messageInfo_InspectContRequest.Size(m)
}
func (m *InspectContRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectContRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InspectContRequest proto.InternalMessageInfo

func (m *InspectContRequest) GetInspectContMsgData() *InspectContMsgData {
	if m != nil {
		return m.InspectContMsgData
	}
	return nil
}

func (m *InspectContRequest) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

type InspectContResponse struct {
	InspectContMsgData   *InspectContMsgData `protobuf:"bytes,1,opt,name=InspectContMsgData" json:"InspectContMsgData,omitempty"`
	Inspection           string              `protobuf:"bytes,2,opt,name=inspection" json:"inspection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InspectContResponse) Reset()         { *m = InspectContResponse{} }
func (m *InspectContResponse) String() string { return proto.CompactTextString(m) }
func (*InspectContResponse) ProtoMessage()    {}
func (*InspectContResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_inspectCont_f57071f177f36f30, []int{2}
}
func (m *InspectContResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectContResponse.Unmarshal(m, b)
}
func (m *InspectContResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectContResponse.Marshal(b, m, deterministic)
}
func (dst *InspectContResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectContResponse.Merge(dst, src)
}
func (m *InspectContResponse) XXX_Size() int {
	return xxx_messageInfo_InspectContResponse.Size(m)
}
func (m *InspectContResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectContResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InspectContResponse proto.InternalMessageInfo

func (m *InspectContResponse) GetInspectContMsgData() *InspectContMsgData {
	if m != nil {
		return m.InspectContMsgData
	}
	return nil
}

func (m *InspectContResponse) GetInspection() string {
	if m != nil {
		return m.Inspection
	}
	return ""
}

func init() {
	proto.RegisterType((*InspectContMsgData)(nil), "protomsgs.InspectContMsgData")
	proto.RegisterType((*InspectContRequest)(nil), "protomsgs.InspectContRequest")
	proto.RegisterType((*InspectContResponse)(nil), "protomsgs.InspectContResponse")
}

func init() {
	proto.RegisterFile("node/protocols/protomsgs/inspectCont.proto", fileDescriptor_inspectCont_f57071f177f36f30)
}

var fileDescriptor_inspectCont_f57071f177f36f30 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0x29, 0x86, 0xb0, 0x72, 0x8b, 0xd3, 0x8b,
	0xf5, 0x33, 0xf3, 0x8a, 0x0b, 0x52, 0x93, 0x4b, 0x9c, 0xf3, 0xf3, 0x4a, 0xf4, 0xc0, 0xa2, 0x42,
	0x9c, 0x70, 0x49, 0x29, 0x55, 0x9c, 0xda, 0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0x3a, 0x94,
	0xfc, 0xb8, 0x84, 0x3c, 0x11, 0xc6, 0xf8, 0x16, 0xa7, 0xbb, 0x24, 0x96, 0x24, 0x0a, 0x59, 0x70,
	0x71, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x82, 0xb8, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0x62, 0x7a, 0x70, 0x33, 0xf4, 0x7c, 0x11, 0xb2, 0x41, 0xc8, 0x4a, 0x95, 0x5a, 0x19, 0x51,
	0x0c, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xf2, 0xc5, 0x66, 0x0d, 0xd4, 0x5c, 0x59,
	0x24, 0x73, 0x31, 0x15, 0x05, 0x61, 0x73, 0x9f, 0x02, 0x17, 0x77, 0x72, 0x7e, 0x5e, 0x49, 0x62,
	0x66, 0x5e, 0x6a, 0x91, 0xa7, 0x8b, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0xb2, 0x90, 0x52,
	0x0b, 0x23, 0x97, 0x30, 0x8a, 0x3b, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xa9, 0xed, 0x10, 0x39,
	0x2e, 0x2e, 0x68, 0x2c, 0x64, 0xe6, 0xe7, 0x41, 0xdd, 0x81, 0x24, 0x92, 0xc4, 0x06, 0x36, 0xd1,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x72, 0xcb, 0x18, 0x47, 0xc5, 0x01, 0x00, 0x00,
}
