// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listContainers.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListContainersMsgData struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListContainersMsgData) Reset()         { *m = ListContainersMsgData{} }
func (m *ListContainersMsgData) String() string { return proto.CompactTextString(m) }
func (*ListContainersMsgData) ProtoMessage()    {}
func (*ListContainersMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_listContainers_6899703f933438ff, []int{0}
}
func (m *ListContainersMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainersMsgData.Unmarshal(m, b)
}
func (m *ListContainersMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainersMsgData.Marshal(b, m, deterministic)
}
func (dst *ListContainersMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainersMsgData.Merge(dst, src)
}
func (m *ListContainersMsgData) XXX_Size() int {
	return xxx_messageInfo_ListContainersMsgData.Size(m)
}
func (m *ListContainersMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainersMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainersMsgData proto.InternalMessageInfo

func (m *ListContainersMsgData) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

// a protocol define a set of reuqest and responses
type ListContainersRequest struct {
	ListContainersMsgData *ListContainersMsgData `protobuf:"bytes,1,opt,name=ListContainersMsgData,proto3" json:"ListContainersMsgData,omitempty"`
	PubKey                string                 `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *ListContainersRequest) Reset()         { *m = ListContainersRequest{} }
func (m *ListContainersRequest) String() string { return proto.CompactTextString(m) }
func (*ListContainersRequest) ProtoMessage()    {}
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listContainers_6899703f933438ff, []int{1}
}
func (m *ListContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainersRequest.Unmarshal(m, b)
}
func (m *ListContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainersRequest.Marshal(b, m, deterministic)
}
func (dst *ListContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainersRequest.Merge(dst, src)
}
func (m *ListContainersRequest) XXX_Size() int {
	return xxx_messageInfo_ListContainersRequest.Size(m)
}
func (m *ListContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainersRequest proto.InternalMessageInfo

func (m *ListContainersRequest) GetListContainersMsgData() *ListContainersMsgData {
	if m != nil {
		return m.ListContainersMsgData
	}
	return nil
}

func (m *ListContainersRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type ListContainersResponse struct {
	ListContainersMsgData *ListContainersMsgData `protobuf:"bytes,1,opt,name=ListContainersMsgData,proto3" json:"ListContainersMsgData,omitempty"`
	ListResult            string                 `protobuf:"bytes,2,opt,name=listResult,proto3" json:"listResult,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *ListContainersResponse) Reset()         { *m = ListContainersResponse{} }
func (m *ListContainersResponse) String() string { return proto.CompactTextString(m) }
func (*ListContainersResponse) ProtoMessage()    {}
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listContainers_6899703f933438ff, []int{2}
}
func (m *ListContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainersResponse.Unmarshal(m, b)
}
func (m *ListContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainersResponse.Marshal(b, m, deterministic)
}
func (dst *ListContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainersResponse.Merge(dst, src)
}
func (m *ListContainersResponse) XXX_Size() int {
	return xxx_messageInfo_ListContainersResponse.Size(m)
}
func (m *ListContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainersResponse proto.InternalMessageInfo

func (m *ListContainersResponse) GetListContainersMsgData() *ListContainersMsgData {
	if m != nil {
		return m.ListContainersMsgData
	}
	return nil
}

func (m *ListContainersResponse) GetListResult() string {
	if m != nil {
		return m.ListResult
	}
	return ""
}

func init() {
	proto.RegisterType((*ListContainersMsgData)(nil), "protomsgs.ListContainersMsgData")
	proto.RegisterType((*ListContainersRequest)(nil), "protomsgs.ListContainersRequest")
	proto.RegisterType((*ListContainersResponse)(nil), "protomsgs.ListContainersResponse")
}

func init() {
	proto.RegisterFile("listContainers.proto", fileDescriptor_listContainers_6899703f933438ff)
}

var fileDescriptor_listContainers_6899703f933438ff = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0xc9, 0x2c, 0x2e,
	0x71, 0xce, 0xcf, 0x2b, 0x49, 0xcc, 0xcc, 0x4b, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x04, 0x53, 0xb9, 0xc5, 0xe9, 0xc5, 0x52, 0x3c, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79,
	0x10, 0x09, 0xa5, 0x40, 0x2e, 0x51, 0x1f, 0x14, 0x0d, 0xbe, 0xc5, 0xe9, 0x2e, 0x89, 0x25, 0x89,
	0x42, 0x16, 0x5c, 0xdc, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x20, 0xae, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0xb7, 0x91, 0x98, 0x1e, 0xdc, 0x1c, 0x3d, 0x5f, 0x84, 0x6c, 0x10, 0xb2, 0x52, 0xa5,
	0x76, 0x46, 0x74, 0x33, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc2, 0x70, 0x58, 0x06,
	0x35, 0x5d, 0x01, 0xc9, 0x74, 0xac, 0xea, 0x82, 0x70, 0xb8, 0x55, 0x8c, 0x8b, 0xad, 0xa0, 0x34,
	0xc9, 0x3b, 0xb5, 0x52, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x53, 0x9a, 0xc0, 0xc8,
	0x25, 0x86, 0xee, 0x92, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x9a, 0x39, 0x45, 0x8e, 0x8b, 0x0b,
	0x14, 0x01, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x50, 0xe7, 0x20, 0x89, 0x24, 0xb1, 0x81, 0xcd,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xaa, 0xc0, 0xc7, 0xa7, 0x01, 0x00, 0x00,
}
