// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uploadImage.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadImageMsgData struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadImageMsgData) Reset()         { *m = UploadImageMsgData{} }
func (m *UploadImageMsgData) String() string { return proto.CompactTextString(m) }
func (*UploadImageMsgData) ProtoMessage()    {}
func (*UploadImageMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_uploadImage_972f658ca41f1c00, []int{0}
}
func (m *UploadImageMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageMsgData.Unmarshal(m, b)
}
func (m *UploadImageMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageMsgData.Marshal(b, m, deterministic)
}
func (dst *UploadImageMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageMsgData.Merge(dst, src)
}
func (m *UploadImageMsgData) XXX_Size() int {
	return xxx_messageInfo_UploadImageMsgData.Size(m)
}
func (m *UploadImageMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageMsgData proto.InternalMessageInfo

func (m *UploadImageMsgData) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

type UploadImageResponse struct {
	UploadImageMsgData   *UploadImageMsgData `protobuf:"bytes,1,opt,name=uploadImageMsgData,proto3" json:"uploadImageMsgData,omitempty"`
	ImageID              string              `protobuf:"bytes,2,opt,name=imageID,proto3" json:"imageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_uploadImage_972f658ca41f1c00, []int{1}
}
func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (dst *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(dst, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

func (m *UploadImageResponse) GetUploadImageMsgData() *UploadImageMsgData {
	if m != nil {
		return m.UploadImageMsgData
	}
	return nil
}

func (m *UploadImageResponse) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadImageMsgData)(nil), "protomsgs.UploadImageMsgData")
	proto.RegisterType((*UploadImageResponse)(nil), "protomsgs.UploadImageResponse")
}

func init() { proto.RegisterFile("uploadImage.proto", fileDescriptor_uploadImage_972f658ca41f1c00) }

var fileDescriptor_uploadImage_972f658ca41f1c00 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2d, 0xc8, 0xc9,
	0x4f, 0x4c, 0xf1, 0xcc, 0x4d, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04,
	0x53, 0xb9, 0xc5, 0xe9, 0xc5, 0x52, 0x3c, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0x10, 0x09, 0x25,
	0x3f, 0x2e, 0xa1, 0x50, 0x84, 0x6a, 0xdf, 0xe2, 0x74, 0x97, 0xc4, 0x92, 0x44, 0x21, 0x0b, 0x2e,
	0xee, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x10, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb,
	0x48, 0x4c, 0x0f, 0x6e, 0x88, 0x9e, 0x2f, 0x42, 0x36, 0x08, 0x59, 0xa9, 0x52, 0x1d, 0x97, 0x30,
	0x92, 0x79, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xbe, 0x5c, 0x42, 0xa5, 0x18,
	0xd6, 0x40, 0xcd, 0x95, 0x45, 0x32, 0x17, 0xd3, 0x2d, 0x41, 0x58, 0x34, 0x0a, 0x49, 0x70, 0xb1,
	0x67, 0x82, 0xf8, 0x9e, 0x2e, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0x6e, 0x12, 0x1b,
	0xd8, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xee, 0x31, 0xe2, 0x04, 0x01, 0x00,
	0x00,
}
