// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node/protocols/protomsgs/task.proto

package protomsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RunImageMsgData struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData" json:"messageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RunImageMsgData) Reset()         { *m = RunImageMsgData{} }
func (m *RunImageMsgData) String() string { return proto.CompactTextString(m) }
func (*RunImageMsgData) ProtoMessage()    {}
func (*RunImageMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_2fb9c2e881efbf56, []int{0}
}
func (m *RunImageMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunImageMsgData.Unmarshal(m, b)
}
func (m *RunImageMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunImageMsgData.Marshal(b, m, deterministic)
}
func (dst *RunImageMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunImageMsgData.Merge(dst, src)
}
func (m *RunImageMsgData) XXX_Size() int {
	return xxx_messageInfo_RunImageMsgData.Size(m)
}
func (m *RunImageMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_RunImageMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_RunImageMsgData proto.InternalMessageInfo

func (m *RunImageMsgData) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

// a protocol define a set of reuqest and responses
type RunRequest struct {
	RunImageMsgData      *RunImageMsgData `protobuf:"bytes,1,opt,name=RunImageMsgData" json:"RunImageMsgData,omitempty"`
	ImageID              string           `protobuf:"bytes,2,opt,name=imageID" json:"imageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_2fb9c2e881efbf56, []int{1}
}
func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (dst *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(dst, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetRunImageMsgData() *RunImageMsgData {
	if m != nil {
		return m.RunImageMsgData
	}
	return nil
}

func (m *RunRequest) GetImageID() string {
	if m != nil {
		return m.ImageID
	}
	return ""
}

type RunResponse struct {
	RunImageMsgData      *RunImageMsgData `protobuf:"bytes,1,opt,name=RunImageMsgData" json:"RunImageMsgData,omitempty"`
	ContainerID          string           `protobuf:"bytes,2,opt,name=containerID" json:"containerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_2fb9c2e881efbf56, []int{2}
}
func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (dst *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(dst, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetRunImageMsgData() *RunImageMsgData {
	if m != nil {
		return m.RunImageMsgData
	}
	return nil
}

func (m *RunResponse) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func init() {
	proto.RegisterType((*RunImageMsgData)(nil), "protomsgs.RunImageMsgData")
	proto.RegisterType((*RunRequest)(nil), "protomsgs.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "protomsgs.RunResponse")
}

func init() {
	proto.RegisterFile("node/protocols/protomsgs/task.proto", fileDescriptor_task_2fb9c2e881efbf56)
}

var fileDescriptor_task_2fb9c2e881efbf56 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xce, 0xcb, 0x4f, 0x49,
	0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0x29, 0x86, 0xb0, 0x72, 0x8b, 0xd3, 0x8b,
	0xf5, 0x4b, 0x12, 0x8b, 0xb3, 0xf5, 0xc0, 0x5c, 0x21, 0x4e, 0xb8, 0xa8, 0x94, 0x2a, 0x4e, 0xf5,
	0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0x10, 0x1d, 0x4a, 0xde, 0x5c, 0xfc, 0x41, 0xa5, 0x79, 0x9e,
	0xb9, 0x89, 0xe9, 0xa9, 0xbe, 0xc5, 0xe9, 0x2e, 0x89, 0x25, 0x89, 0x42, 0x16, 0x5c, 0xdc, 0xb9,
	0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x20, 0xae, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x98,
	0x1e, 0xdc, 0x00, 0x3d, 0x5f, 0x84, 0x6c, 0x10, 0xb2, 0x52, 0xa5, 0x1c, 0x2e, 0xae, 0xa0, 0xd2,
	0xbc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x17, 0x0c, 0xa3, 0xa1, 0x66, 0x49, 0x21,
	0x99, 0x85, 0xa6, 0x22, 0x08, 0xc3, 0x35, 0x12, 0x5c, 0xec, 0x99, 0x20, 0xbe, 0xa7, 0x8b, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x54, 0xca, 0xc5, 0x0d, 0xb6, 0xad, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x95, 0x4a, 0xd6, 0x29, 0x70, 0x71, 0x27, 0xe7, 0xe7, 0x95, 0x24, 0x66, 0xe6,
	0xa5, 0x16, 0xc1, 0xad, 0x44, 0x16, 0x4a, 0x62, 0x03, 0x9b, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x86, 0xb5, 0x10, 0x3a, 0x91, 0x01, 0x00, 0x00,
}
