[global]
log_level = "info"
data_dir = "gocc_data"
database_name = "gocc_db"
availability = ["10:00-19:00", "20:00-23:00"]

[host]
max_containers = 10
cpu_per_container = 2
gpu_per_container = 2
memory_per_container = 1024
storage_per_container = 4096
    [host.network]
    ip = "10.0.0.1"

[rpc]
enabled = true
enabled_services = ["discovery"]
whitelist = ["*"]
    [rpc.socket]
    enabled = true
    path = ""

    [rpc.http]
    enabled = true
    listen_port = 8082
    cross_origin_value = "*"
    listen_address = "localhost"

    [rpc.websocket]
    enabled = true
    listen_port = 8081
    cross_origin_value = "*"
    listen_address = "localhost"
       
[p2p]
max_peers = 20
listen_port = 10244
connection_timeout = 60
min_peers_threashold = 30
listen_address = "localhost"
    [p2p.bootstraper]
    nodes = ["localhost","192.168.3.12"]
    bootstrap_periodic = 30
